refactor: pass a list of reports to coverage-to-md script

diff --git a/.github/scripts/test-coverage/coverage-to-md b/.github/scripts/test-coverage/coverage-to-md
--- a/.github/scripts/test-coverage/coverage-to-md
+++ b/.github/scripts/test-coverage/coverage-to-md
@@ -3,19 +3,17 @@
 # coverage-to-md - Convert coverage report JSON to Markdown format
 #
 # Usage:
-#   coverage-to-md [options] <arguments>
+#   coverage-to-md <coverage-reports>
 #
-# Mandatory arguments to long options are mandatory for short options too.
-#   -d, --dir=DIR       Directory containing coverage report JSON files
-#   -f, --file=FILE     Single coverage report JSON file
+# Arguments:
+#   <coverage-reports>  Space-separated list of coverage report JSON files
 #
 # Exit codes:
 #   0   Success
 #   1   General error
 #
 # Examples:
-#   coverage-to-md -d /path/to/coverage/reports
-#   coverage-to-md -f /path/to/coverage/report.json
+#   coverage-to-md /path/to/coverage/report1.json /path/to/coverage/report2.json
 
 set -euo pipefail
 
@@ -57,84 +55,39 @@ function json_to_md {
 function main {
     echo "### Test Coverage"
 
-    local dir=""
-    local file=""
+    total=0
+    count=0
 
-    # Read arguments
-    while [[ $# -gt 0 ]]; do
-        case $1 in
-            -d|--dir)
-                shift
-                dir="$1"
-                ;;
-            -f|--file)
-                shift
-                file="$1"
-                ;;
-            *)
-                echo "Unknown argument: $1" >&2
-                echo "Usage: $0 -d <dir> | -f <file>" >&2
-                exit 1
-                ;;
-        esac
-        shift
+    md_body=""
+    for file in "$@" ; do
+        if [[ ! -f "$file" ]]; then
+            echo "Error: File not found - $file" >&2
+            exit 1
+        fi
+
+        file_total=$(jq -r '.total_coverage' <$file)
+        total=$(echo "$total + $file_total" | bc)
+        count=$((count + 1))
+
+        arch=$(jq -r '.arch' < "$file")
+        filename=$(basename -- "$file")
+        
+        md_body+="---"$'\n'
+
+        if [[ -n "$arch" && "$arch" != "null" ]]; then
+            md_body+="#### Arch: ${arch}"$'\n'
+        else
+            md_body+="#### Coverage File: ${filename}"$'\n'
+        fi
+        
+        md_body+="$(json_to_md "$file")"$'\n\n'
     done
 
-    # Process directory
-    if [[ -n "$dir" ]]; then
-        if [[ ! -d "$dir" ]]; then
-            echo "Directory not found: $dir" >&2
-            exit 1
-        fi
-
-        total=0
-        count=0
-
-        md_body=""
-        for file in "$dir"/*.json; do
-            file_total=$(jq -r '.total_coverage' <$file)
-            total=$(echo "$total + $file_total" | bc)
-            count=$((count + 1))
-
-            arch=$(jq -r '.arch' < "$file")
-            filename=$(basename -- "$file")
-            
-            md_body+="---"$'\n'
-
-            if [[ -n "$arch" && "$arch" != "null" ]]; then
-                md_body+="#### Arch: ${arch}"$'\n'
-            else
-                md_body+="#### Coverage File: ${filename}"$'\n'
-            fi
-            
-            md_body+="$(json_to_md "$file")"$'\n\n'
-        done
-
-        # If there are no files, exit early
-        if [ $count -eq 0 ]; then
-            echo "No JSON files found in directory: $dir" >&2
-            exit 1
-        fi
-
-        # Create the Markdown output
-        average=$(echo "scale=2; $total / $count" | bc)
-        echo "Average Total Coverage: ${average}%"
-        echo ""
-        echo "$md_body"
-
-
-    # Process single file
-    elif [[ -n "$file" ]]; then
-        if [[ ! -f "$file" ]]; then
-            echo "File not found: $file" >&2
-            exit 1
-        fi
-
-        total=$(jq -r '.total_coverage' < "$file")
-        echo "Total Coverage: ${total}%"
-        echo ""
-        json_to_md "$file"
-    fi
+    # Create the Markdown output
+    average=$(echo "scale=2; $total / $count" | bc)
+    echo "Average Total Coverage: ${average}%"
+    echo ""
+    echo "$md_body"
 }
 
 main "$@"
