feat(24.10): add SDF for cpio

diff --git a/tests/spread/integration/cpio/task.yaml b/tests/spread/integration/cpio/task.yaml
--- a/tests/spread/integration/cpio/task.yaml
+++ b/tests/spread/integration/cpio/task.yaml
@@ -1,16 +1,26 @@
 summary: Integration tests for cpio
 
-execute: |
-  rootfs="$(install-slices cpio_bins)"
+environment:
+  SLICE/cpio: "cpio"
+  SLICE/mt: "mt-gnu"
 
-  chroot "${rootfs}/" cpio --help
-  chroot "${rootfs}/" mt-gnu --help
-  mkdir "${rootfs}/foo"
-  echo "xyz" > "${rootfs}/testfile" | \
-  echo "testfile" | \
-    chroot "${rootfs}/" cpio -ov | \
-    chroot "${rootfs}/" cpio -iv -D foo
-  if [ ! -e "${rootfs}/foo/testfile" ]; then
-    echo "cpio failed"
-    exit 1
-  fi
+execute: |
+  rootfs="$(install-slices cpio_${SLICE})"
+  case ${SLICE} in
+    cpio)
+      chroot "${rootfs}/" cpio --help
+      mkdir "${rootfs}/foo"
+      echo "xyz" > "${rootfs}/testfile"
+      echo "testfile" | \
+      chroot "${rootfs}/" cpio -ov | \
+      chroot "${rootfs}/" cpio -iv -D foo
+      if [ ! -e "${rootfs}/foo/testfile" ]; then
+        echo "cpio failed"
+        exit 1
+      fi
+      test "$(cat ${rootfs}/testfile)" = "$(cat ${rootfs}/foo/testfile)"
+    ;;
+    mt-gnu)
+      chroot "${rootfs}/" mt-gnu --help
+    ;;
+  esac
