chore: backport #929

diff --git a/tests/spread/lib/install-slices b/tests/spread/lib/install-slices
--- a/tests/spread/lib/install-slices
+++ b/tests/spread/lib/install-slices
@@ -1,4 +1,4 @@
-#!/bin/bash -ex
+#!/bin/bash -e
 # spellchecker: ignore rootfs
 
 # Installs one or more slices into a dynamically created temporary path.
@@ -11,8 +11,7 @@ function main() {
     slices="${slices} base-files_chisel"
 
     local rootfs="$(mktemp -d)"
-    #shellcheck disable=SC2086
-    chisel cut --release "$PROJECT_PATH" --root "$rootfs" $slices
+    chisel_cut "$rootfs" "$slices"
     [ -n "$MANIFESTS_EXPORT_DIR" ] && export_manifests "$rootfs" "$MANIFESTS_EXPORT_DIR"
 
     echo "${rootfs}"
@@ -32,6 +31,52 @@ function export_manifests() {
     mkdir -p "$export_dir"
     local seq=$(find "$export_dir" -type f -name 'manifest_*.wall' | wc -l)
     cp "$rootfs/var/lib/chisel/manifest.wall" "$export_dir/manifest_$(printf "%05d" "$seq").wall"
+}
+
+_PATTERNS_TO_RETRY=(
+    # https://github.com/canonical/chisel-releases/issues/765
+    "cannot fetch from archive"
+    # https://github.com/canonical/chisel-releases/issues/766
+    "cannot talk to archive"
+    # https://github.com/canonical/chisel-releases/issues/768
+    "cannot find archive data"
+)
+
+function chisel_cut() {
+    # chisel cut with retry logic for known transient errors
+    local rootfs="$1"
+    local slices="$2"
+
+    local n_retries=3
+    local attempt
+
+    local output=$(mktemp)
+    for ((attempt=1; attempt<=n_retries; attempt++)); do
+        #shellcheck disable=SC2086
+        chisel cut \
+            --ignore=unstable \
+            --release "$PROJECT_PATH" \
+            --root "$rootfs" \
+            $slices \
+            2>&1 | tee "$output" >&2
+        [[ "${PIPESTATUS[0]}" -eq 0 ]] && break
+
+        local matched=""
+        for pattern in "${_PATTERNS_TO_RETRY[@]}"; do
+            if grep -q "$pattern" "$output"; then
+                matched="$pattern"
+                break
+            fi
+        done
+
+        if [ $attempt -lt $n_retries ] && [ -n "$matched" ]; then
+            echo "Warning: Error while installing $slices (attempt $attempt/$n_retries). Retrying..." >&2
+            continue
+        else
+            echo "Failed to cut slices. See above for details." >&2
+            exit 1
+        fi
+    done
 }
 
 main "$@"
